tasks:
  - init: |
      echo 'Initialising Project'
    command: |
      echo 'Commanding Project'
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
